### ISSUE TITLE
BE - Signin and Signup

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-carrot#11]
- [x] User model -> name,email, hashed password (bcrypt), 
- [x] /register 
    - [x] Validation (4xx) (password length, email formatting, confirm password is the same as password), create a new user (201), generate a JWT token, return the user and the token (stored in the front-end in local or 
    - [x] /login 
        - [x] verify password / email and return 200, generate a JWT token, return the user and the token (stored in the **front-end** in local or sessionStorage)

**Comment by Manpreet1502** [comment]
Paths and their details are

1) /user/register
	method: POST
	body: you need to send json 
	{
		"name": "test"
    		"email": "test@gmail.com",
    		"password": "test@123"
		"passwordConfirmation": "test@123"
   
	}




 2) /user/login
	 method: POST
	 body:	 you need to send json 
	{
    		"email": "test@gmail.com",
    		"password": "test@123"		   
	}
