### ISSUE TITLE
BE - adding new items

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-carrot#15]
- [x] Item’s model 
    - [x] Picture urls, names, prices (array with a date of when fetched)
    - [x] Prices: [{date: datetime, value: float}]
- [x] POST /items
    - [x] Create a new item (no functionality related to lists)
    - [x] Associate the new item with the user

**Comment by Walihossain** [comment]
Hey Manpreet, did you push the code, as in make the pull request for this ticket?

**Comment by Manpreet1502** [comment]
the route for post request of items is http://localhost:3001/item
->First login as an existing user
-> create a header "x-auth-token" and put the generated token as its value
-> send json in body. ex:
{
	"url":"https://www.amazon.ca/dp/B000L2DSLK/ref=s9_acsd_bw_wf_a_hsy_cdi_11?pf_rd_m=A1IM4EOPHS76S7&pf_rd_s=merchandised-search-12&pf_rd_r=DDSMAYTB1DZC75J04E4W&pf_rd_t=101&pf_rd_p=ab19a05f-0012-4861-a0c1-5758342e523e&pf_rd_i=402123011",
	"name":"Wilson Traditional Soccer Ball",
	"prices": [
		{
		"value": 32.7
		},
		{
		"value": 30.6
		}
		] 
	
}
