### ISSUE TITLE
BE - Get notifications

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-carrot#33]
Returns all notifications of a user

**Comment by Manpreet1502** [comment]
As discussed please log in with the user as discussed

GET request with url : http://localhost:4000/notification

you get the output as an example as:

[
    {
        "_id": "5d9ff12f3d6aadee5c760fb5",
        "user": "5d8a78bdb3296e65606d15b4",
        "item": "5d9aac9416f56592d4d99360",
        "previousPrice": 50,
        "newPrice": 26.56,
        "__v": 0
    },
    {
        "_id": "5d9ff26c417f65c3f039d760",
        "user": "5d8a78bdb3296e65606d15b4",
        "item": "5d9aac9416f56592d4d99360",
        "previousPrice": 30,
        "newPrice": 26.56,
        "__v": 0
    }
]

**Comment by Walihossain** [comment]
@Manpreet1502 : Would it be possible to add the item name here.
