### ISSUE TITLE
BE - Adding new item

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-carrot#35]
For the same user, each list should have a unique name

You need two routes:
1st route gets the url, scrapes it and returns the details
2nd route takes the details, creates the item/stores it in the db, returns a success status

**Comment by Manpreet1502** [comment]
Added 2 post routes
As have been doing earlier, login with the user

Routes:

1) /item/scrapeItem 
you need to send url in the body: ex-
{
   "url": "https://www.amazon.ca/dp/B072KLMKTK/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B072KLMKTK&pd_rd_w=fTEjS&pf_rd_p=4b7c8c1c-293f-4b1e-a49a-8787dff31bcb&pd_rd_wg=YEBIB&pf_rd_r=CZETKVE6SGXQKHJ8SNN7&pd_rd_r=d3a44b22-2a2b-4911-b827-daf3bc1c690b&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzT1hIVUJJR0RGV1REJmVuY3J5cHRlZElkPUEwODU3NDk0MVNDM0MxTlM4MjY1MiZlbmNyeXB0ZWRBZElkPUEwMzc0NzAxWjI0VFlFRE5SSUlBJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ=="
}

- you will get the scaped details in return as follows:

{
    "name": "NESTLÉ MINIS Assorted Bars - KITKAT, Coffee Crisp, AERO, Smarties - 1.02kg (Pack of 100 Mini Bars)",
    "prices": [
        {
            "price": "CDN$ 16.98",
            "date": "2019-10-07T20:39:14.798Z"
        }
    ],
    "url": "https://images-na.ssl-images-amazon.com/images/I/512v6Hk9qyL._AC_.jpg"
}

2) /item/storeItem

you need to send the item object that you have received from scraping of following type:

{
	"url":"https://www.amazon.ca/NESTL%C3%89-MINIS-Assorted-Bars-Smarties/dp/B073PCGJ6L?smid=A3DWYIK6Y9EEQB&pf_rd_p=3d9cc557-75f7-4454-b582-4516ea214290&pf_rd_r=9MGC3AC60WTABTSCGGGR",
	"name":"MAKO 2",
	"list_name":"5dfa173f119c57f532759914d338da28266bb292.png",
	"prices": [
		{
		"date": "2019-10-07T20:39:14.798Z"
		"value": 10.00
		},
		
	]

}

- in return you will receive json as follows:
{
    "msg": "item has been added to the list"
}

**Comment by Manpreet1502** [comment]
UPDATED:

As have been doing earlier, login with the user

Routes:

1) /item/scrapeItem
you need to send url in the body: ex-
	{	
		"url": "https://www.amazon.ca/gp/product/B07SFKTLZM?pd_rd_w=gQeg7&pf_rd_p=1cab0319-91ce-4e39-9b55-7e6823a7612c&pf_rd_r=BW95VJE1G71PW8CEGGGQ&pd_rd_r=4fd935ad-c270-49d0-8f73-cd421076ad59&pd_rd_wg=BcizJ"

	}
Response:
{
    "name": "Xbox Elite Wireless Controller Series 2",
    "prices": [
        {
            "value": "229.96",
            "date": "2019-10-12T22:35:14.312Z"
        }
    ],
    "pictureUrl": "https://images-na.ssl-images-amazon.com/images/I/71vNw0EbrTL._SX522_.jpg",
    "url": "https://www.amazon.ca/gp/product/B07SFKTLZM?pd_rd_w=gQeg7&pf_rd_p=1cab0319-91ce-4e39-9b55-7e6823a7612c&pf_rd_r=BW95VJE1G71PW8CEGGGQ&pd_rd_r=4fd935ad-c270-49d0-8f73-cd421076ad59&pd_rd_wg=BcizJ"
}


2) /item/storeItem
you need to send the item object that you have received from scraping of following type:

{
  "list_name": "5dfa173f119c57f532759914d338da28266bb292.png",
  "name": "Xbox Elite Wireless Controller Series 2",
    "prices": [
        {
            "value": "229.96",
            "date": "2019-10-12T22:22:36.845Z"
        }
    ],
    "pictureUrl": "https://images-na.ssl-images-amazon.com/images/I/71vNw0EbrTL._SX522_.jpg",
    "url": "https://www.amazon.ca/gp/product/B07SFKTLZM?pd_rd_w=gQeg7&pf_rd_p=1cab0319-91ce-4e39-9b55-7e6823a7612c&pf_rd_r=BW95VJE1G71PW8CEGGGQ&pd_rd_r=4fd935ad-c270-49d0-8f73-cd421076ad59&pd_rd_wg=BcizJ"
}

Response:
{
    "msg": "item has been added to the list"
}
